---
server:
  port: 8080
  contextPath: /spring-boot-ng-crud
---
spring:
  profiles: local,default
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/spring-boot-ng
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

